#version 450
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

struct VkDispatchIndirectCommand {
	uint x, y, z;
};

layout(constant_id = 0) const uint kIndex = 0;
layout(binding = 0) uniform uuCount { uint uCount[kIndex + 1]; };
layout(std430, binding = 1) writeonly buffer uuCommand { VkDispatchIndirectCommand uCommand; };

void main() { uCommand = VkDispatchIndirectCommand((uCount[kIndex] + 127) / 128, 1, 1); }
