#version 450
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

#include "Constant.glsl"

struct VkDispatchIndirectCommand {
	uint x, y, z;
};
layout(binding = 0) uniform uuCount { uint uCount; };
layout(std430, binding = 1) writeonly buffer uuCommand { VkDispatchIndirectCommand uCommand; };

void main() { uCommand = VkDispatchIndirectCommand(min(uCount, NRC_TRAIN_BATCH_SIZE) / 128, 1, 1); }
